[package]
name = "n-puzzle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
ndarray = "0.16.1"
pathfinding = "4.13.0"

[profile.release]
debug = true
